env:
  DOCKER_BUILDKIT: "1"
  COMPOSE_DOCKER_CLI_BUILD: "1"
  BUILDKIT_PROGRESS: "plain"
  NO_SQUASH: ""
  NO_SILENT: "1"
  NONINTERACTIVE: "1"
  FORCE_ONLINE: "1"
  NBPARALLEL: "2"
  RELEASABLE_REPOS: "^corpusops/"
  RELEASABLE_BRANCHES: "^(refs/heads/)?(master|2.0|workflows)$"
  COPS_URL: "https://github.com/corpusops/corpusops.bootstrap"
  COPS_ROOT: "${{github.workspace}}/local/corpusops.bootstrap"
  silent: "$COPS_ROOT/bin/cops_shell_common output_in_error silent_vv"
  DOCKER_RELEASER: "${{ secrets.DOCKER_HUB_USERNAME }}"
  DOCKER_PASSWORD: "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}"
jobs:
  r:
    runs-on: ubuntu-20.04
    env: {IMAGES: "${{matrix.IMAGES}}"}
    steps:
      - name: Set vars
        run: |-
            if ( echo "$GITHUB_REF" | egrep -q "${RELEASABLE_BRANCHES}" ) \
            && ( echo "$GITHUB_REPOSITORY" | egrep -q "${RELEASABLE_REPOS}" )
            then releasable=true;else releasable=false;fi
            echo "releasable=$releasable" >> $GITHUB_OUTPUT
            echo "silent=$(echo $silent)" >> $GITHUB_OUTPUT
        id: v
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Activate docker experimental
        run: |-
          sudo bash -exc "service docker stop;python -c \
          \"d='/etc/docker/daemon.json';\
          import json;c=json.load(open(d));c['experimental']=True;\
          open(d, 'w').write(json.dumps(c))\"
          systemctl restart docker"
      - uses: actions/checkout@v3
      - name: Cache multiple paths
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache
            local
          key: 6-${{ runner.os }}-${{ github.ref }}-${{ github.repository }}-venvstatics
      - name: setup
        run: set -e;i=$(whoami);sudo sh -c "chown -Rf $i .";
             sudo sh -c 'sed -i -re 's/azure.//' /etc/apt/sources.list && apt-get update -qq' && ./main.sh refresh_corpusops;
             sudo sh -c 'sed -i -re 's/azure.//' /etc/apt/sources.list && apt-get update -qq && apt-get install -qqy --force-yes parallel'
      - name: refresh images
        run: set -e;if (echo $IMAGES|grep -q zleftover);then
             rm -f */*/*/Dockerfile&&${{steps.v.outputs.silent}} ./refresh_images.sh;
             fi
      - name: build & release
        run: set -e;
             if [ "x${{steps.v.outputs.releasable}}" = "xtrue" ];then export DO_RELEASE=1;fi;
             ./build.sh $IMAGES
# ${{steps.v.outputs.silent}} ./build.sh $IMAGES
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        IMAGES:
        - "corpusops/postgis-bare/13-3 corpusops/postgis-bare/12-3 corpusops/postgis-bare/12-2.5 corpusops/postgis-bare/11-3 corpusops/postgis-bare/11-2.5 corpusops/postgis-bare/10-2.4 corpusops/postgis-bare/10-2.5 corpusops/postgis-bare/10-3 corpusops/postgis-bare/9.0-2.1 corpusops/postgis-bare/9.1-2.2 corpusops/postgis-bare/9.2-2.2 corpusops/postgis-bare/9.2-2.3 corpusops/postgis-bare/9.3-2.3 corpusops/postgis-bare/9.3-2.4 corpusops/postgis-bare/9.4-2.3 corpusops/postgis-bare/9.4-2.5 corpusops/postgis-bare/9.5-2.4 corpusops/postgis-bare/9.5-2.5 corpusops/postgis-bare/9.6-2.4 corpusops/postgis-bare/9.6-2.5 corpusops/postgis-bare/9.4-2.4"
        - "corpusops/postgis-bare/13-3-alpine corpusops/postgis-bare/12-3-alpine corpusops/postgis-bare/12-2.5-alpine corpusops/postgis-bare/11-3-alpine corpusops/postgis-bare/11-2.5-alpine corpusops/postgis-bare/10-2.4-alpine corpusops/postgis-bare/10-2.5-alpine corpusops/postgis-bare/10-3-alpine corpusops/postgis-bare/9.6-2.4-alpine corpusops/postgis-bare/9.6-2.5-alpine"
on:
  push:
  workflow_dispatch:
  schedule: [{cron: '1 0 2,4,6,16,18,20 * *'}]
